project_id = "asjmszuwfaiqbnnvgmrc"

[functions.send-event-notifications]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
